parameters:

services:
    screeper.action.services.action:
        class: Screeper\ActionBundle\Services\ActionService
        arguments:
            - '@service_container'
            - '@doctrine.orm.entity_manager'